### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered ?

### ISSUE THREAD

**Issue by Someonetoldme584** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#163]
```
To create a public link, set `share=True` in `launch()`.
Startup time: 26.2s (prepare environment: 6.2s, import torch: 5.2s, import gradio: 0.8s, setup paths: 0.7s, initialize shared: 0.7s, other imports: 0.6s, load scripts: 10.7s, create ui: 0.7s, gradio launch: 0.4s).
Loading VAE weights specified in settings: D:\AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: sdp... done.
Model loaded in 3.6s (load weights from disk: 0.8s, create model: 0.5s, apply weights to model: 1.7s, load VAE: 0.3s, calculate empty prompt: 0.2s).
Exporting epicphotogasm_zUniversal to TensorRT
{'sample': [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)], 'timesteps': [(1,), (2,), (8,)], 'encoder_hidden_states': [(1, 77, 768), (2, 77, 768), (8, 154, 768)]}
No ONNX file found. Exporting ONNX...
Disabling attention optimization
D:\AI\stable-diffusion-webui\venv\lib\site-packages\einops\einops.py:314: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  known = {axis for axis in composite_axis if axis_name2known_length[axis] != _unknown_axis_length}
D:\AI\stable-diffusion-webui\venv\lib\site-packages\einops\einops.py:315: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  unknown = {axis for axis in composite_axis if axis_name2known_length[axis] == _unknown_axis_length}
D:\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py:158: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
D:\AI\stable-diffusion-webui\modules\sd_hijack_unet.py:26: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if a.shape[-2:] != b.shape[-2:]:
D:\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py:109: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[E] ONNX-Runtime is not installed, so constant folding may be suboptimal or not work at all.
    Consider installing ONNX-Runtime: D:\AI\stable-diffusion-webui\venv\Scripts\python.exe -m pip install onnxruntime
[I] Folding Constants | Pass 1
[!] Module: 'onnxruntime.tools.symbolic_shape_infer' is required but could not be imported.
    Note: Error was: No module named 'onnxruntime'
    You can set POLYGRAPHY_AUTOINSTALL_DEPS=1 in your environment variables to allow Polygraphy to automatically install missing modules.
[W] Falling back to `onnx.shape_inference` because `onnxruntime.tools.symbolic_shape_infer` either could not be loaded or did not run successfully.
    Note that using ONNX-Runtime for shape inference may be faster and require less memory.
    Consider installing ONNX-Runtime or setting POLYGRAPHY_AUTOINSTALL_DEPS=1 in your environment variables to allow Polygraphy to do so automatically.
[W] Attempting to run shape inference on a large model (1641.0 MiB). This may require a large amount of memory.
    If memory consumption becomes too high, the process may be killed. You may want to try disabling shape inference in that case.
[I]     Total Nodes | Original:  8992, After Folding:  6216 |  2776 Nodes Folded
[I] Folding Constants | Pass 2
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[W] Inference failed. You may want to try enabling partitioning to see better results. Note: Error was:
No module named 'onnxruntime'
[!] Module: 'onnxruntime.tools.symbolic_shape_infer' is required but could not be imported.
    Note: Error was: No module named 'onnxruntime'
    You can set POLYGRAPHY_AUTOINSTALL_DEPS=1 in your environment variables to allow Polygraphy to automatically install missing modules.
[W] Attempting to run shape inference on a large model (1642.0 MiB). This may require a large amount of memory.
    If memory consumption becomes too high, the process may be killed. You may want to try disabling shape inference in that case.
[I]     Total Nodes | Original:  6216, After Folding:  5928 |   288 Nodes Folded
[I] Folding Constants | Pass 3
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[W] Inference failed. You may want to try enabling partitioning to see better results. Note: Error was:
No module named 'onnxruntime'
[!] Module: 'onnxruntime.tools.symbolic_shape_infer' is required but could not be imported.
    Note: Error was: No module named 'onnxruntime'
    You can set POLYGRAPHY_AUTOINSTALL_DEPS=1 in your environment variables to allow Polygraphy to automatically install missing modules.
[I]     Total Nodes | Original:  5928, After Folding:  5928 |     0 Nodes Folded
Exported to ONNX.
Building TensorRT engine... This can take a while, please check the progress in the terminal.
Building TensorRT engine for D:\AI\stable-diffusion-webui\models\Unet-onnx\epicphotogasm_zUniversal_f00b95d9.onnx: D:\AI\stable-diffusion-webui\models\Unet-trt\epicphotogasm_zUniversal_f00b95d9_cc86_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 1721925659
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 1721925659
[I] Loading tactic timing cache from D:\AI\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
[I] Building engine with configuration:
    Flags                  | [FP16, REFIT, TF32]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 4095.50 MiB, TACTIC_DRAM: 4095.50 MiB]
    Tactic Sources         | [CUBLAS, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.LAYER_NAMES_ONLY
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
Building engine:  50%|█████████████████████████████████▌                                 | 3/6 [00:00<00:00,  6.77it/s][W] UNSUPPORTED_STATESkipping tactic 0 due to insufficient memory on requested size of 22215426048 detected for tactic 0x0000000000000000. costs:   0%|                                                                   | 0/5 [00:00<?, ?it/s]
Timing tactics:   0%|                                                                            | 0/3 [00:00<?, ?it/s][E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)4%|████████▎                                                    | 64/472 [00:23<01:05,  6.26it/s]
[W] Requested amount of GPU memory (3227516928 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[W] UNSUPPORTED_STATESkipping tactic 0 due to insufficient memory on requested size of 3227516928 detected for tactic 0x0000000000000000.
                                                                                                                       [E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)8%|██████████▉                                                  | 85/472 [00:33<01:38,  3.93it/s]
                                                                                                                       [E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)1%|██████████████████████████████████████████▍                 | 334/472 [01:10<00:13, 10.29it/s]
                                                                                                                       [E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)6%|█████████████████████████████████████████████▌              | 358/472 [01:14<00:11,  9.91it/s]
[E] 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::allocate::20] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[W] Requested amount of GPU memory (41954813 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[E] 9: Skipping tactic0x0000000000000000 due to exception [::0] autotuning: User allocator error allocating 41954813-byte buffer
[W] Unable to determine GPU memory usage: an illegal memory access was encountered
[E] 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::allocate::20] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[E] 9: Skipping tactic0x0000000000000000 due to exception [::0] autotuning: User allocator error allocating 41954813-byte buffer
Building engine:  50%|█████████████████████████████████▌                                 | 3/6 [01:15<01:15, 25.22s/it][E] 10: Could not find any implementation for node {ForeignNode[onnx::LayerNormalization_10900 + ONNXTRT_Broadcast_3525.../output_blocks.7/output_blocks.7.1/Reshape_2 + /output_blocks.7/output_blocks.7.1/Transpose_1 + /output_blocks.7/output_blocks.7.1/Reshape_3]}.
Building engine: 100%|███████████████████████████████████████████████████████████████████| 6/6 [01:15<00:00, 12.62s/it]
[E] 1: [cudaResources.cpp::nvinfer1::ScopedCudaStream::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::4040] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[onnx::LayerNormalization_10900 + ONNXTRT_Broadcast_3525.../output_blocks.7/output_blocks.7.1/Reshape_2 + /output_blocks.7/output_blocks.7.1/Transpose_1 + /output_blocks.7/output_blocks.7.1/Reshape_3]}.)
[!] Invalid Engine. Please ensure the engine was built correctly
ERROR:root:Failed to build engine: Invalid Engine. Please ensure the engine was built correctly
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 152, in export_unet_to_trt
    ret = export_trt(
  File "D:\AI\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 158, in export_trt
    shared.sd_model = model.cuda()
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 73, in cuda
    return super().cuda(device=device)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

**Comment by chazzhou** [comment]
Your card does not have enough VRAM to build engines.

**Comment by CoderCowMoo** [comment]
Hey, I had this same error too, but I was able to compile the default settings. When I tried replicating them (but for 256-512, I thought this would reduce VRAM consumption), it didn't allow it. Additionally, is it normal for it to consume ~70GB of memory?

**Comment by xuzihe2010** [comment]
I got the similar failure but the error messages were slightly different: 

It kept complaining about:

**[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed**

I'm not sure if this is also because of no enough VRAM or something else. My GPU is GTX 1080 8GB, CUDA version 11.8, Nvidia drive 546.33

Could anyone shed some light on this? The complete logs from SD WebUI terminal is attached.

```Exporting tmndMix_tmndMixSPLightPruned to TensorRT
{'sample': [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)], 'timesteps': [(1,), (2,), (8,)], 'encoder_hidden_states': [(1, 77, 768), (2, 77, 768), (8, 154, 768)]}
No ONNX file found. Exporting ONNX...
Disabling attention optimization
C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\einops\einops.py:314: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  known = {axis for axis in composite_axis if axis_name2known_length[axis] != _unknown_axis_length}
C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\einops\einops.py:315: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  unknown = {axis for axis in composite_axis if axis_name2known_length[axis] == _unknown_axis_length}
C:\sd_webui_aki\sd-webui-aki-v4.4\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py:158: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
C:\sd_webui_aki\sd-webui-aki-v4.4\modules\sd_hijack_unet.py:26: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if a.shape[-2:] != b.shape[-2:]:
C:\sd_webui_aki\sd-webui-aki-v4.4\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py:109: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============

verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[I] Folding Constants | Pass 1
[I]     Total Nodes | Original:  8992, After Folding:  6216 |  2776 Nodes Folded

[I] Folding Constants | Pass 2
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored

[W] Inference failed. You may want to try enabling partitioning to see better results. Note: Error was:
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: D:\a\_work\1\s\onnxruntime\core\graph\model.cc:146 onnxruntime::Model::Model Unsupported model IR version: 9, max supported IR version: 8
[I]     Total Nodes | Original:  6216, After Folding:  5864 |   352 Nodes Folded

[I] Folding Constants | Pass 3
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[W] Inference failed. You may want to try enabling partitioning to see better results. Note: Error was:
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: D:\a\_work\1\s\onnxruntime\core\graph\model.cc:146 onnxruntime::Model::Model Unsupported model IR version: 9, max supported IR version: 8
[I]     Total Nodes | Original:  5864, After Folding:  5864 |     0 Nodes Folded

Exported to ONNX.
Building TensorRT engine... This can take a while, please check the progress in the terminal.
Building TensorRT engine for C:\sd_webui_aki\sd-webui-aki-v4.4\models\Unet-onnx\tmndMix_tmndMixSPLightPruned_838796b6.onnx: C:\sd_webui_aki\sd-webui-aki-v4.4\models\Unet-trt\tmndMix_tmndMixSPLightPruned_838796b6_cc61_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 1721936614
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 1721936614
[I] Loading tactic timing cache from C:\sd_webui_aki\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc61.cache
WARNING:root:Timing cache file C:\sd_webui_aki\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc61.cache not found, falling back to empty timing cache.
[I] Building engine with configuration:
    Flags                  | [REFIT, TF32]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 8191.88 MiB, TACTIC_DRAM: 8191.88 MiB]
    Tactic Sources         | [CUBLAS, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.LAYER_NAMES_ONLY
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device

[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::96] Error Code 1: Cuda Driver (an illegal memory access was encountered)
[E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::96] Error Code 1: Cuda Driver (an illegal memory access was encountered)
[E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::96] Error Code 1: Cuda Driver (an illegal memory access was encountered)
[E] 2: Impossible to reformat.
[E] 1: [cudaResources.cpp::nvinfer1::ScopedCudaStream::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (an illegal memory access was encountered)

[E] 2: [optimizer.cpp::nvinfer1::builder::cgraph::CopyingLeafNode::computeCosts::4404] Error Code 2: Internal Error (Impossible to reformat.)
[!] Invalid Engine. Please ensure the engine was built correctly
ERROR:root:Failed to build engine: Invalid Engine. Please ensure the engine was built correctly
Traceback (most recent call last):
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 152, in export_unet_to_trt
    ret = export_trt(
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 158, in export_trt
    shared.sd_model = model.cuda()
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 73, in cuda
    return super().cuda(device=device)
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: an illegal memory access was encountered
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.```

**Comment by USElessOFF** [comment]
> Я получил аналогичный сбой, но сообщения об ошибках были немного другими:
> 
> Он продолжал жаловаться на:
> 
> **[E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось**
> 
> Я не уверен, что это также из-за недостаточного VRAM или чего-то еще. Мой GPU GTX 1080 8GB, CUDA версии 11.8, Nvidia диск 546.33
> 
> Кто-нибудь может пролить свет на это, пожалуйста? Прилагаются полные журналы с терминала SD WebUI.
> 
> ```
> {'образец': [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)], 'timesteps': [(1,), (2,), (8,)], 'encoder_hidden_states': [(1, 77, 768), (2, 77, 768), (8, 154, 768)]}
> Файл ONNX не найден. Экспорт ОННХ...
> Отключение оптимизации внимания
> C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\einops\einops.py:314: TracerWarning: Преобразование тензора в булеан Python может привести к неправильному следу. Мы не можем записать поток данных значений Python, поэтому это значение будет рассматриваться как константа в будущем. Это означает, что след может не обобщаться на другие входы!
>   известен = {axis для оси в композите_axis if axis_name2known_length[axis] != _unknown_axis_lenge}
> C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\einops\einops.py:315: TracerWarning: Преобразование тензора в булеан Python может привести к неправильному следу. Мы не можем записать поток данных значений Python, поэтому это значение будет рассматриваться как константа в будущем. Это означает, что след может не обобщаться на другие входы!
>   неизвестен = {axis для оси в композите_axis if axis_name2known_length[axis] == _unknown_axis_length}
> C:\sd_webui_aki\sd-webui-aki-v4.4\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py:158: TracerWarning: Преобразование тензора в булевый Python может привести к неправильному следу. Мы не можем записать поток данных значений Python, поэтому это значение будет рассматриваться как константа в будущем. Это означает, что след может не обобщаться на другие входы!
>   утвердить x.shape[1] == само.каналов
> C:\sd_webui_aki\sd-webui-aki-v4.4\modules\sd_hijack_unet.py:26: TracerWarning: Преобразование тензора в Python boolean может привести к неправильному следу. Мы не можем записать поток данных значений Python, поэтому это значение будет рассматриваться как константа в будущем. Это означает, что след может не обобщаться на другие входы!
>   если a.shape[-2:] != b.shape[-2:]:
> C:\sd_webui_aki\sd-webui-aki-v4.4\репозитории\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py:109: TracerWarning: Преобразование тензора в Python boolean может привести к неправильному следу. Мы не можем записать поток данных значений Python, поэтому это значение будет рассматриваться как константа в будущем. Это означает, что след может не обобщаться на другие входы!
>   утвердить x.shape[1] == само.каналов
> =========== Diagnostic Run torch.onnx.export версия 2.0.1=cu118 =+==========
> 
> многословный: Ложный, уровень журнала: Уровень.ERROR
> ==================== 0 NONE 0 NOTE 0 ПРЕДУПРЕЖДЕНИЕ 0 ОШИБКА =========================
> 
> [W] 'colored' модуль не установлен, не будет использовать цвета при регистрации. Чтобы включить цвета, пожалуйста, установите модуль 'colored': python3 -m pip установите цветные
> [I] Складные константы | Pass 1
> [I] Total Nodes | Original: 8992, After Folding: 6216 | 2776 Nodes Folded
> 
> [I] Складные константы | Pass 2
> [W] цветной модуль не установлен, не будет использовать цвета при регистрации. Чтобы включить цвета, пожалуйста, установите цветной модуль: python3 -m pip установите цветной
> 
> [W] Ссылка не удалась. Вы можете попробовать включить разбиение, чтобы увидеть лучшие результаты. Примечание: Ошибка была:
> [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Не удалось загрузить модель с ошибкой: D:\a\_work\1\s\onnxruntime\core\graph\model.cc:146 onnxruntime::Model::Model Неподдерживаемая модель IR версии: 9, максимальная поддерживаемая версия ИК: 8
> [I] Total Nodes | Original: 6216, After Folding: 5864 | 352 Nodes Folded
> 
> [I] Складные константы | Pass 3
> [W] цветной модуль не установлен, не будет использовать цвета при регистрации. Чтобы включить цвета, пожалуйста, установите цветной модуль: python3 -m pip установите цветной
> [W] Ссылка не удалась. Вы можете попробовать включить разбиение, чтобы увидеть лучшие результаты. Примечание: Ошибка была:
> [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Не удалось загрузить модель с ошибкой: D:\a\_work\1\s\onnxruntime\core\graph\model.cc:146 onnxruntime::Model::Model Неподдерживаемая модель IR версии: 9, максимальная поддерживаемая версия ИК: 8
> [I]     Total Nodes | Оригинал: 5864, После Сложения: 5864 | 0 Узлы Сложенные
> 
> Экспортируется в ONNX.
> Построение двигателя TensorRT... Это может занять некоторое время, пожалуйста, проверьте прогресс в терминале.
> Построение движка TensorRT для C:\sd_webui_aki\sd-webui-aki-v4.4\моделей\Unet-onnx\tmndMix_tmndMixSPLightPruned_838796b6.onnx: C:\sd_webui_aki\sd-webui-aki-v4.4\модели\Unet-trt\tmndMix_tmndMixSPLightPruned_838796b6_cc61_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x7768+8x154x768.trt
> [libprotobuf ПРЕДУПРЕЖДЕНИЕ **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Чтение опасно большого сообщения протокола.  Если сообщение окажется больше 2147483647 байт, разбор будет остановлен по соображениям безопасности.  Чтобы увеличить лимит (или отключить эти предупреждения), см. CodedInputStream::SetTotalBytesLimit() в google/protobuf/io/coded_stream.h.
> [libprotobuf ПРЕДУПРЕЖДЕНИЕ **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] Общее количество прочитанных байтов составило 1721936614
> [libprotobuf ПРЕДУПРЕЖДЕНИЕ **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Чтение опасно большого сообщения протокола.  Если сообщение окажется больше 2147483647 байт, разбор будет остановлен по соображениям безопасности.  Чтобы увеличить лимит (или отключить эти предупреждения), см. CodedInputStream::SetTotalBytesLimit() в google/protobuf/io/coded_stream.h.
> [libprotobuf ПРЕДУПРЕЖДЕНИЕ **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] Общее количество прочитанных байтов составило 1721936614
> [I] Загрузка тактического тайминга кэша из C:\sd_webui_aki\sd-webui-aki-v4.4\расширения\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc61.кэш
> ПРЕДУПРЕЖДЕНИЕ:root:Timing кэш-файл C:\sd_webui_aki\sd-webui-aki-v4.4\расширения\Stable-Diffusion-WebUI-TensorRT\timing_caces\timing_cache_win_cc61.cache не найден, возвращаясь к пустому тайминг-кешу.
> [I] Строительный двигатель с конфигурацией:
>     Флаги | [REFIT, TF32]
>     Ёмкость двигателя | EngineCapability.DEFAULT
>     Бассейны памяти | [WORKSPACE: 8191.88 MiB, TACTIC_DRAM: 8191.88 MiB]
>     Тактические Источники | [CUBLAS, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
>     Профилирование Глагольность | ПрофилированиеВербость.LAYER_NAMES_ONLY
>     Предварительный просмотр Особенности | [FASTER_DYNAMIC_SHAPES_0805, ОТКЛЮЧИТЬ_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> 
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x0000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003e8 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 9: Пропуск тактики0x0000000000003ea из-за исключения Внутренний cuTensor permutate выполнить не удалось
> [E] 9: Пропуск тактики0x00000000000000000 из-за исключения изображение ядра не доступно для выполнения на устройстве
> [E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(структ CUmod_st *)>::operator ():96] Код ошибки 1: Cuda Driver (встречался незаконный доступ к памяти)
> [E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(структ CUmod_st *)>::operator ():96] Код ошибки 1: Cuda Driver (встречался незаконный доступ к памяти)
> [E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(структ CUmod_st *)>::operator ():96] Код ошибки 1: Cuda Driver (встречался незаконный доступ к памяти)
> [E] 2: Невозможно переформатировать.
> [E] 1: [cudaResources.cpp::nvinfer1::ScopedCudaStream::~ScopedCudaStream::47] Код ошибки 1: Cuda Runtime (был обнаружен незаконный доступ к памяти)
> 
> [E] 2: [optimizer.cpp::nvinfer1::строитель::cgraph::CopyingLeafNode::computeCosts::4404] Код ошибки 2: Внутренняя ошибка (Невозможно переформатировать.)
> [!] Инвалидный Двигатель. Пожалуйста, убедитесь, что двигатель был построен правильно
> ERROR:root:Не удалось построить двигатель: Invalid Engine. Пожалуйста, убедитесь, что двигатель был построен правильно
> Трекбек (последний звонок):
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", строка 488, в run_predict
>     вывод = ожидание app.get_blocks().process_api(
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", строка 1431, in process_api
>     результат = ждут self.call_function(
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", строка 1103, в call_function
>     прогноз = ждут anyio.to_thread.run_sync(
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", строка 31, в run_sync
>     возврат ожиданий get_asynclib(.run_sync_in_worker_thread(
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", строка 937, в run_sync_in_worker_thread
>     возвращение в будущее
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", строка 867, в запуске
>     результат = context.run(func, *args)
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", строка 707, в обертке
>     ответ = f(*args, **kwargs)
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\расширения\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", строка 152, in export_unet_to_trt
>     ret = export_trt(
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\расширения\Stable-Diffusion-WebUI-TensorRT\exporter.py", строка 158, in export_trt
>     shared.sd_model = model.cuda()
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", строка 73, in cuda
>     возвращение super().cuda(device=device)
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\модули\module.py", строка 905, in cuda
>     вернуть self._apply(lambda t: t.cuda(устройство))
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", строка 797, in _apply
>     модуль._apply(fn)
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", строка 797, in _apply
>     модуль._apply(fn)
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", строка 797, in _apply
>     модуль._apply(fn)
>   [Предыдущая линия повторяется еще 1 раз]
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", строка 820, in _apply
>     param_применяется = fn(парам)
>   Файл "C:\sd_webui_aki\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", строка 905, в <lambda>
>     вернуть self._apply(lambda t: t.cuda(устройство))
> RuntimeError: Ошибка CUDA: был обнаружен незаконный доступ к памяти
> 提鬼: Пятхон 运行时出了一个常。АМПЛУА ርト ⁇ 面。
> Ошибки ядра CUDA могут быть асинхронно сообщены при каком-либо другом вызове API, поэтому стектрейс ниже может быть неверным.
> Для отладки рассмотрим прохождение CUDA_LAUNCH_BLOCKING=1.
> Компилируйте с `TORCH_USE_CUDA_DSA`, чтобы включить утверждения на стороне устройства.``
> ```

Have a similar problem on similar card, 
but i tried to set this args in my webui:
_set POLYGRAPHY_AUTOINSTALL_DEPS=1
set CUDA_LAUNCH_BLOCKING=1
set CUDA_VISIBLE_DEVICES=0
set CUDA_MODULE_LOADING=LAZY_
not helped for me, and I was trying change CUDA System Fallback Policy in 3D settings NVIDIA, i discovered it in nvidia forum, but..., not worked for me

**Comment by NikkeTryHard** [comment]
same

**Comment by NikkeTryHard** [comment]
for me this occurred when i was using multi diffusion upscale extension with 512-768 dynamic model, i know im not supposed to use another extension with tensorrt

**Comment by stanislav-malchev** [comment]
nVidia GeForce GTX 1070 Ti with 8GB of VRAM.
Same error:
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
