### ISSUE TITLE
Specific CPU, unable to perform inference engine.

### ISSUE THREAD

**Issue by GarrisonDivision** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#165]
The graphics card is GPU 1, NVIDIA Tesla P4.

Driver Version: 31.0.15.2824
Driver Date: 2023/1/15
DirectX Version: 12 (FL 12.1)
Physical Location: PCI Bus 2, Device 0, Function 0

Utilization: 0%
Dedicated GPU Memory: 1.1/8.0 GB
Shared GPU Memory: 0.1/9.8 GB
Total GPU Memory: 1.1/17.8 GB

After running for a period of time, an error is displayed

ERROR:root:Failed to build engine: Invalid Engine. Please ensure the engine was built correctly
Traceback (most recent call last):
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 152, in export_unet_to_trt
    ret = export_trt(
  File "F:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 158, in export_trt
    shared.sd_model = model.cuda()
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 73, in cuda
    return super().cuda(device=device)
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 918, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "F:\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 918, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: an illegal memory access was encountered
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by GarrisonDivision** [comment]
I am using an integrated package, and the error displayed by the launcher is:
Extension Version:
The extension version you have installed is incompatible with the SD-WebUI version. Please go to the version management and extension management interface to manually align the update dates.

CUDA Exception:
An unrecoverable exception occurred during CUDA execution, which may be caused by software errors, driver issues, GPU core or memory faults, etc. Please try restarting the system and check the graphics card status.

Unsupported Graphics Card:
The current operation does not support the graphics card you are currently using.

**Comment by GarrisonDivision** [comment]
The console is reporting an error:
FP16 has been disabled because your GPU does not support it.
Exporting AnythingV5Ink_ink to TensorRT
{'sample': [(1, 4, 32, 32), (2, 4, 64, 64), (2, 4, 64, 64)], 'timesteps': [(1,), (2,), (2,)], 'encoder_hidden_states': [(1, 77, 768), (2, 77, 768), (2, 154, 768)]}
Building TensorRT engine... This can take a while, please check the progress in the terminal.
Building TensorRT engine for F:\sd-webui-aki-v4.4\models\Unet-onnx\AnythingV5Ink_ink_a45eb6e9.onnx: F:\sd-webui-aki-v4.4\models\Unet-trt\AnythingV5Ink_ink_a45eb6e9_cc61_sample=1x4x32x32+2x4x64x64+2x4x64x64-timesteps=1+2+2-encoder_hidden_states=1x77x768+2x77x768+2x154x768.trt
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 1721936614
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 1721936614
[I] Loading tactic timing cache from F:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc61.cache
WARNING:root:Timing cache file F:\sd-webui-aki-v4.4\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc61.cache not found, falling back to empty timing cache.
[I] Building engine with configuration:
    Flags                  | [REFIT, TF32]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 8191.88 MiB, TACTIC_DRAM: 8191.88 MiB]
    Tactic Sources         | [CUBLAS, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.LAYER_NAMES_ONLY
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003e8 due to exception no kernel image is available for execution on the device
[E] 9: Skipping tactic0x00000000000003ea due to exception Internal cuTensor permutate execute failed
[E] 9: Skipping tactic0x0000000000000000 due to exception no kernel image is available for execution on the device
[E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::96] Error Code 1: Cuda Driver (an illegal memory access was encountered)
[E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::96] Error Code 1: Cuda Driver (an illegal memory access was encountered)
[E] 1: [cudaDriverHelpers.cpp::nvinfer1::CuDeleter<struct CUmod_st *,&enum cudaError_enum __cdecl nvinfer1::cuModuleUnloadWrapper(struct CUmod_st *)>::operator ()::96] Error Code 1: Cuda Driver (an illegal memory access was encountered)
[E] 2: Impossible to reformat.
[E] 1: [cudaResources.cpp::nvinfer1::ScopedCudaStream::~ScopedCudaStream::47] Error Code 1: Cuda Runtime (an illegal memory access was encountered)
[E] 2: [optimizer.cpp::nvinfer1::builder::cgraph::CopyingLeafNode::computeCosts::4404] Error Code 2: Internal Error (Impossible to reformat.)
[!] Invalid Engine. Please ensure the engine was built correctly

**Comment by contentis** [comment]
What engine are you trying to build and what is the GPU? I'm assuming you're running out of memory

**Comment by aretaareta24** [comment]
I have the same problem on my RTX 2060 12GB, can you help 
![Cuplikan layar 2023-11-21 021124](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/145859583/9dc8f48a-13e3-4492-ac7e-8301618e6261)
?

**Comment by GarrisonDivision** [comment]
> 你想构建什么引擎，GPU是什么？我假设你的内存不足
I increased the physical memory to 32GB
Not really

**Comment by GarrisonDivision** [comment]
> I have the same problem on my RTX 2060 12GB, can you help ![Cuplikan layar 2023-11-21 021124](https://user-images.githubusercontent.com/145859583/284367184-9dc8f48a-13e3-4492-ac7e-8301618e6261.png) ?

I don't know either. If you find a solution, please reply to me.

**Comment by GarrisonDivision** [comment]
> What engine are you trying to build and what is the GPU? I'm assuming you're running out of memory

I increased the physical memory to 32GB
Not really

**Comment by rickytaber** [comment]
same problem also :(
