### ISSUE TITLE
No ''Available TensorRT Engine Profiles''

### ISSUE THREAD

**Issue by sprk34** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#17]
I have exported engine but I don't see any profile under "TensorRT Engine Profiles" selection and it gives me this error when export an engine.

```
 Building engine:  50%|#####     | 3/6 [00:00<00:00, 1[E] 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::allocate::20] Error Code 1: Cuda Runtime (out of memory)        | 0/5 [00:00<?, ?it/s]
[W] Requested amount of GPU memory (34360788477 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[E] 9: Skipping tactic0x0000000000000000 due to exception [::0] autotuning: User allocator error allocating 34360788477-byte buffer
[E] 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::allocate::20] Error Code 1: Cuda Runtime (out of memory)
[E] 9: Skipping tactic0x0000000000000000 due to exception [::0] autotuning: User allocator error allocating 34360788477-byte buffer
[W] UNSUPPORTED_STATESkipping tactic 0 due to insufficient memory on requested size of 9261154304 detected for tactic 0x0000000000000000.
[E] 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::allocate::20] Error Code 1: Cuda Runtime (out of memory)
[E] 9: Skipping tactic0x0000000000000000 due to exception [::0] autotuning: User allocator error allocating 34360788477-byte buffer
[E] 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::allocate::20] Error Code 1: Cuda Runtime (out of memory)
[E] 9: Skipping tactic0x0000000000000000 due to exception [::0] autotuning: User allocator error allocating 34360788477-byte buffer
[E] 1: [defaultAllocator.cpp::nvinfer1::internal::DefaultAllocator::allocate::20] Error Code 1: Cuda Runtime (out of memory)
[E] 9: Skipping tactic0x0000000000000000 due to exception [::0] autotuning: User allocator error allocating 34360788477-byte buffer
Building engine: 100%|##########| 6/6 [02:52<00:00, 28.76s/it]
[I] Finished engine building in 173.326 seconds
[I] Saving tactic timing cache to C:\Users\DjSpa\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
[I] Saving engine to C:\Users\DjSpa\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\models\Unet-trt\unrealRealism_v40_d1c341b5_cc86_sample=1x4x96x96+2x4x128x128+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt            
```                                               
I can see exported models in the''Unet-onnx'' and ''Unet-trt'' folders but there is no ''trt'' files on ''sd_unet'' sections. I have only ''Automatic'' and ''None'' and sometimes it stucks at ''[INFO]: No ONNX file found. Exporting ONNX…'' and i had to restart webui. then same error.
I have 3070ti if that matters.
 
![asdf51](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/148280740/e08bced9-392f-4273-89af-98618fe28196)
![adsadas](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/148280740/cdba6d6c-2ed2-4ca0-ba6d-c37cb6fa7eca)

**Comment by racerx2oo3** [comment]
It looks like your engine profiles didn't get written into the model.json file, I suspect that if you open the model.json file it will empty.

You can try deleting all files in the Unet-trt folder including the model.json file and the rebuild your trt engines.

**Comment by sprk34** [comment]
> It looks like your engine profiles didn't get written into the model.json file, I suspect that if you open the model.json file it will empty.
> 
> You can try deleting all files in the Unet-trt folder including the model.json file and then rebuild your trt engines.

I tried but this time it gaves me this error

> ONNX-Runtime is not installed, so constant folding may be suboptimal or not work at all.
>     Consider installing ONNX-Runtime: C:\Users\DjSpa\AppData\Roaming\StabilityMatrix\Packages\stable-diffusion-webui\venv\Scripts\python.exe -m pip install onnxruntime
> [I] Folding Constants | Pass 1
> [!] Module: 'onnxruntime.tools.symbolic_shape_infer' is required but could not be imported.
>     Note: Error was: No module named 'onnxruntime'
>     You can set POLYGRAPHY_AUTOINSTALL_DEPS=1 in your environment variables to allow Polygraphy to automatically install missing modules.
> [I]     Total Nodes | Original:  8992, After Folding:  6216 |  2776 Nodes Folded
> [I] Folding Constants | Pass 2
> [W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
> [W] Inference failed. You may want to try enabling partitioning to see better results. Note: Error was:
> No module named 'onnxruntime'
> [!] Module: 'onnxruntime.tools.symbolic_shape_infer' is required but could not be imported.
>     Note: Error was: No module named 'onnxruntime'
>     You can set POLYGRAPHY_AUTOINSTALL_DEPS=1 in your environment variables to allow Polygraphy to automatically install missing modules.
> [I]     Total Nodes | Original:  6216, After Folding:  6152 |    64 Nodes Folded
> [I] Folding Constants | Pass 3
> [W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
> [W] Inference failed. You may want to try enabling partitioning to see better results. Note: Error was:
> No module named 'onnxruntime'
> [!] Module: 'onnxruntime.tools.symbolic_shape_infer' is required but could not be imported.
>     Note: Error was: No module named 'onnxruntime'
>     You can set POLYGRAPHY_AUTOINSTALL_DEPS=1 in your environment variables to allow Polygraphy to automatically install missing modules.
> [I]     Total Nodes | Original:  6152, After Folding:  6152 |     0 Nodes Folded

I'll try to delete all the files that comes with tensort-rt in''venv'' and will reinstall it. Thanx for reply.

**Comment by racerx2oo3** [comment]
Unless the engine generation actually failed, those errors are more likely just warnings and things should still work as expected.

**Comment by sprk34** [comment]
> Unless the engine generation actually failed, those errors are more likely just warnings and things should still work as expected.

Didn't know that thank you, but still no luck, You are right about ''model json'' file. It is still empty.I have no clue what the problem and will never understand probably:) Thank you anyway

**Comment by sprk34** [comment]
I solved the issue by disabling --api. It was enabled by default. I actually dont know what it does exacly but i disabled that and it worked.

**Comment by contentis** [comment]
> ''[INFO]: TensorRT engine found. Skipping build. You can enable Force Export in the Advanced Settings to force a rebuild if needed.''

To avoid this, you'll need to delete the engine from Unet-trt. 

I have not yet reproduced this issue. I'll work on this as soon as possible, but due to the amount of issues and limited time this might need some time to be fixed.

**Comment by RoombaVoid** [comment]
> I solved the issue by disabling --api. It was enabled by default. I actually dont know what it does exacly but i disabled that and it worked.
Thank you that fixed my Unet not showing up.

**Comment by contentis** [comment]
I've documented that `--api` can cause issues when exporting in the readme now. I'll close as this seems to be resolved. Feel free to reopen is you still encounter issues.
